/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as StoreRequiredRouteImport } from './routes/_store-required'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as StoreRouteImport } from './routes/$store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation.$id'
import { Route as StoreRequiredCartRouteImport } from './routes/_store-required/cart'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as ProductsSlugIndexRouteImport } from './routes/products.$slug.index'
import { Route as StoreRequiredCheckoutIndexRouteImport } from './routes/_store-required/checkout.index'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app.index'
import { Route as ApiMercadopagoConnectRouteImport } from './routes/api/mercadopago/connect'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StoreRequiredProductsAllRouteImport } from './routes/_store-required/products.all'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed/app/settings'
import { Route as AuthedAppReviewsRouteImport } from './routes/_authed/app/reviews'
import { Route as AuthedAppProductOptionTypesRouteImport } from './routes/_authed/app/product-option-types'
import { Route as AuthedAppDeliveryFeesRouteImport } from './routes/_authed/app/delivery-fees'
import { Route as AuthedAppCategoriesRouteImport } from './routes/_authed/app/categories'
import { Route as ordersOrdersIdRouteImport } from './routes/(orders)/orders.$id'
import { Route as AuthedAppProductsIndexRouteImport } from './routes/_authed/app/products/index'
import { Route as AuthedAppOrdersIndexRouteImport } from './routes/_authed/app/orders.index'
import { Route as AuthedAppInventoryIndexRouteImport } from './routes/_authed/app/inventory.index'
import { Route as AuthedAppDashboardIndexRouteImport } from './routes/_authed/app/dashboard/index'
import { Route as AuthedAppCustomersIndexRouteImport } from './routes/_authed/app/customers.index'
import { Route as AuthedAppCouponsIndexRouteImport } from './routes/_authed/app/coupons/index'
import { Route as AuthedAppProductsNewRouteImport } from './routes/_authed/app/products/new'
import { Route as AuthedAppOrdersIdRouteImport } from './routes/_authed/app/orders.$id'
import { Route as AuthedAppInventoryAdjustmentRouteImport } from './routes/_authed/app/inventory.adjustment'
import { Route as AuthedAppCustomersCustomerIdRouteImport } from './routes/_authed/app/customers.$customerId'
import { Route as AuthedAppCouponsNewRouteImport } from './routes/_authed/app/coupons/new'
import { Route as ordersOrdersOrderIdConfirmationRouteImport } from './routes/(orders)/orders.$orderId.confirmation'
import { Route as AuthedAppProductsIdDetailsRouteImport } from './routes/_authed/app/products.$id.details'
import { Route as AuthedAppProductsVariantsIdEditRouteImport } from './routes/_authed/app/products.variants.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRequiredRoute = StoreRequiredRouteImport.update({
  id: '/_store-required',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/$store',
  path: '/$store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRequiredCartRoute = StoreRequiredCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRequiredRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/products/$slug/',
  path: '/products/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRequiredCheckoutIndexRoute =
  StoreRequiredCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => StoreRequiredRoute,
  } as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const ApiMercadopagoConnectRoute = ApiMercadopagoConnectRouteImport.update({
  id: '/api/mercadopago/connect',
  path: '/api/mercadopago/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRequiredProductsAllRoute =
  StoreRequiredProductsAllRouteImport.update({
    id: '/products/all',
    path: '/products/all',
    getParentRoute: () => StoreRequiredRoute,
  } as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppReviewsRoute = AuthedAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProductOptionTypesRoute =
  AuthedAppProductOptionTypesRouteImport.update({
    id: '/product-option-types',
    path: '/product-option-types',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppDeliveryFeesRoute = AuthedAppDeliveryFeesRouteImport.update({
  id: '/delivery-fees',
  path: '/delivery-fees',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCategoriesRoute = AuthedAppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedAppRoute,
} as any)
const ordersOrdersIdRoute = ordersOrdersIdRouteImport.update({
  id: '/(orders)/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppProductsIndexRoute = AuthedAppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOrdersIndexRoute = AuthedAppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInventoryIndexRoute = AuthedAppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppDashboardIndexRoute = AuthedAppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCustomersIndexRoute = AuthedAppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCouponsIndexRoute = AuthedAppCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppProductsNewRoute = AuthedAppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppOrdersIdRoute = AuthedAppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppInventoryAdjustmentRoute =
  AuthedAppInventoryAdjustmentRouteImport.update({
    id: '/inventory/adjustment',
    path: '/inventory/adjustment',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppCustomersCustomerIdRoute =
  AuthedAppCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppCouponsNewRoute = AuthedAppCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const ordersOrdersOrderIdConfirmationRoute =
  ordersOrdersOrderIdConfirmationRouteImport.update({
    id: '/(orders)/orders/$orderId/confirmation',
    path: '/orders/$orderId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedAppProductsIdDetailsRoute =
  AuthedAppProductsIdDetailsRouteImport.update({
    id: '/products/$id/details',
    path: '/products/$id/details',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppProductsVariantsIdEditRoute =
  AuthedAppProductsVariantsIdEditRouteImport.update({
    id: '/products/variants/$id/edit',
    path: '/products/variants/$id/edit',
    getParentRoute: () => AuthedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthedAppRouteWithChildren
  '/cart': typeof StoreRequiredCartRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/orders/$id': typeof ordersOrdersIdRoute
  '/app/categories': typeof AuthedAppCategoriesRoute
  '/app/delivery-fees': typeof AuthedAppDeliveryFeesRoute
  '/app/product-option-types': typeof AuthedAppProductOptionTypesRoute
  '/app/reviews': typeof AuthedAppReviewsRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/products/all': typeof StoreRequiredProductsAllRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mercadopago/connect': typeof ApiMercadopagoConnectRoute
  '/app/': typeof AuthedAppIndexRoute
  '/checkout/': typeof StoreRequiredCheckoutIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/orders/$orderId/confirmation': typeof ordersOrdersOrderIdConfirmationRoute
  '/app/coupons/new': typeof AuthedAppCouponsNewRoute
  '/app/customers/$customerId': typeof AuthedAppCustomersCustomerIdRoute
  '/app/inventory/adjustment': typeof AuthedAppInventoryAdjustmentRoute
  '/app/orders/$id': typeof AuthedAppOrdersIdRoute
  '/app/products/new': typeof AuthedAppProductsNewRoute
  '/app/coupons/': typeof AuthedAppCouponsIndexRoute
  '/app/customers/': typeof AuthedAppCustomersIndexRoute
  '/app/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/app/inventory/': typeof AuthedAppInventoryIndexRoute
  '/app/orders/': typeof AuthedAppOrdersIndexRoute
  '/app/products/': typeof AuthedAppProductsIndexRoute
  '/app/products/$id/details': typeof AuthedAppProductsIdDetailsRoute
  '/app/products/variants/$id/edit': typeof AuthedAppProductsVariantsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/cart': typeof StoreRequiredCartRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/orders/$id': typeof ordersOrdersIdRoute
  '/app/categories': typeof AuthedAppCategoriesRoute
  '/app/delivery-fees': typeof AuthedAppDeliveryFeesRoute
  '/app/product-option-types': typeof AuthedAppProductOptionTypesRoute
  '/app/reviews': typeof AuthedAppReviewsRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/products/all': typeof StoreRequiredProductsAllRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mercadopago/connect': typeof ApiMercadopagoConnectRoute
  '/app': typeof AuthedAppIndexRoute
  '/checkout': typeof StoreRequiredCheckoutIndexRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
  '/orders/$orderId/confirmation': typeof ordersOrdersOrderIdConfirmationRoute
  '/app/coupons/new': typeof AuthedAppCouponsNewRoute
  '/app/customers/$customerId': typeof AuthedAppCustomersCustomerIdRoute
  '/app/inventory/adjustment': typeof AuthedAppInventoryAdjustmentRoute
  '/app/orders/$id': typeof AuthedAppOrdersIdRoute
  '/app/products/new': typeof AuthedAppProductsNewRoute
  '/app/coupons': typeof AuthedAppCouponsIndexRoute
  '/app/customers': typeof AuthedAppCustomersIndexRoute
  '/app/dashboard': typeof AuthedAppDashboardIndexRoute
  '/app/inventory': typeof AuthedAppInventoryIndexRoute
  '/app/orders': typeof AuthedAppOrdersIndexRoute
  '/app/products': typeof AuthedAppProductsIndexRoute
  '/app/products/$id/details': typeof AuthedAppProductsIdDetailsRoute
  '/app/products/variants/$id/edit': typeof AuthedAppProductsVariantsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_store-required': typeof StoreRequiredRouteWithChildren
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/_authed/app': typeof AuthedAppRouteWithChildren
  '/_store-required/cart': typeof StoreRequiredCartRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/(orders)/orders/$id': typeof ordersOrdersIdRoute
  '/_authed/app/categories': typeof AuthedAppCategoriesRoute
  '/_authed/app/delivery-fees': typeof AuthedAppDeliveryFeesRoute
  '/_authed/app/product-option-types': typeof AuthedAppProductOptionTypesRoute
  '/_authed/app/reviews': typeof AuthedAppReviewsRoute
  '/_authed/app/settings': typeof AuthedAppSettingsRoute
  '/_store-required/products/all': typeof StoreRequiredProductsAllRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mercadopago/connect': typeof ApiMercadopagoConnectRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_store-required/checkout/': typeof StoreRequiredCheckoutIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/(orders)/orders/$orderId/confirmation': typeof ordersOrdersOrderIdConfirmationRoute
  '/_authed/app/coupons/new': typeof AuthedAppCouponsNewRoute
  '/_authed/app/customers/$customerId': typeof AuthedAppCustomersCustomerIdRoute
  '/_authed/app/inventory/adjustment': typeof AuthedAppInventoryAdjustmentRoute
  '/_authed/app/orders/$id': typeof AuthedAppOrdersIdRoute
  '/_authed/app/products/new': typeof AuthedAppProductsNewRoute
  '/_authed/app/coupons/': typeof AuthedAppCouponsIndexRoute
  '/_authed/app/customers/': typeof AuthedAppCustomersIndexRoute
  '/_authed/app/dashboard/': typeof AuthedAppDashboardIndexRoute
  '/_authed/app/inventory/': typeof AuthedAppInventoryIndexRoute
  '/_authed/app/orders/': typeof AuthedAppOrdersIndexRoute
  '/_authed/app/products/': typeof AuthedAppProductsIndexRoute
  '/_authed/app/products/$id/details': typeof AuthedAppProductsIdDetailsRoute
  '/_authed/app/products/variants/$id/edit': typeof AuthedAppProductsVariantsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$store'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/app'
    | '/cart'
    | '/accept-invitation/$id'
    | '/categories/$slug'
    | '/checkout/$id'
    | '/pay/$token'
    | '/reviews/new'
    | '/onboarding/'
    | '/orders/$id'
    | '/app/categories'
    | '/app/delivery-fees'
    | '/app/product-option-types'
    | '/app/reviews'
    | '/app/settings'
    | '/products/all'
    | '/api/auth/$'
    | '/api/mercadopago/connect'
    | '/app/'
    | '/checkout/'
    | '/products/$slug/'
    | '/orders/$orderId/confirmation'
    | '/app/coupons/new'
    | '/app/customers/$customerId'
    | '/app/inventory/adjustment'
    | '/app/orders/$id'
    | '/app/products/new'
    | '/app/coupons/'
    | '/app/customers/'
    | '/app/dashboard/'
    | '/app/inventory/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/products/$id/details'
    | '/app/products/variants/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$store'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/cart'
    | '/accept-invitation/$id'
    | '/categories/$slug'
    | '/checkout/$id'
    | '/pay/$token'
    | '/reviews/new'
    | '/onboarding'
    | '/orders/$id'
    | '/app/categories'
    | '/app/delivery-fees'
    | '/app/product-option-types'
    | '/app/reviews'
    | '/app/settings'
    | '/products/all'
    | '/api/auth/$'
    | '/api/mercadopago/connect'
    | '/app'
    | '/checkout'
    | '/products/$slug'
    | '/orders/$orderId/confirmation'
    | '/app/coupons/new'
    | '/app/customers/$customerId'
    | '/app/inventory/adjustment'
    | '/app/orders/$id'
    | '/app/products/new'
    | '/app/coupons'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/orders'
    | '/app/products'
    | '/app/products/$id/details'
    | '/app/products/variants/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$store'
    | '/_authed'
    | '/_store-required'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/_authed/app'
    | '/_store-required/cart'
    | '/accept-invitation/$id'
    | '/categories/$slug'
    | '/checkout/$id'
    | '/pay/$token'
    | '/reviews/new'
    | '/onboarding/'
    | '/(orders)/orders/$id'
    | '/_authed/app/categories'
    | '/_authed/app/delivery-fees'
    | '/_authed/app/product-option-types'
    | '/_authed/app/reviews'
    | '/_authed/app/settings'
    | '/_store-required/products/all'
    | '/api/auth/$'
    | '/api/mercadopago/connect'
    | '/_authed/app/'
    | '/_store-required/checkout/'
    | '/products/$slug/'
    | '/(orders)/orders/$orderId/confirmation'
    | '/_authed/app/coupons/new'
    | '/_authed/app/customers/$customerId'
    | '/_authed/app/inventory/adjustment'
    | '/_authed/app/orders/$id'
    | '/_authed/app/products/new'
    | '/_authed/app/coupons/'
    | '/_authed/app/customers/'
    | '/_authed/app/dashboard/'
    | '/_authed/app/inventory/'
    | '/_authed/app/orders/'
    | '/_authed/app/products/'
    | '/_authed/app/products/$id/details'
    | '/_authed/app/products/variants/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  StoreRequiredRoute: typeof StoreRequiredRouteWithChildren
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  PayTokenRoute: typeof PayTokenRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ordersOrdersIdRoute: typeof ordersOrdersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMercadopagoConnectRoute: typeof ApiMercadopagoConnectRoute
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
  ordersOrdersOrderIdConfirmationRoute: typeof ordersOrdersOrderIdConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store-required': {
      id: '/_store-required'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$store': {
      id: '/$store'
      path: '/$store'
      fullPath: '/$store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store-required/cart': {
      id: '/_store-required/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreRequiredCartRouteImport
      parentRoute: typeof StoreRequiredRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/products/$slug'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store-required/checkout/': {
      id: '/_store-required/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof StoreRequiredCheckoutIndexRouteImport
      parentRoute: typeof StoreRequiredRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/api/mercadopago/connect': {
      id: '/api/mercadopago/connect'
      path: '/api/mercadopago/connect'
      fullPath: '/api/mercadopago/connect'
      preLoaderRoute: typeof ApiMercadopagoConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store-required/products/all': {
      id: '/_store-required/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof StoreRequiredProductsAllRouteImport
      parentRoute: typeof StoreRequiredRoute
    }
    '/_authed/app/settings': {
      id: '/_authed/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/reviews': {
      id: '/_authed/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AuthedAppReviewsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/product-option-types': {
      id: '/_authed/app/product-option-types'
      path: '/product-option-types'
      fullPath: '/app/product-option-types'
      preLoaderRoute: typeof AuthedAppProductOptionTypesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/delivery-fees': {
      id: '/_authed/app/delivery-fees'
      path: '/delivery-fees'
      fullPath: '/app/delivery-fees'
      preLoaderRoute: typeof AuthedAppDeliveryFeesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/categories': {
      id: '/_authed/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AuthedAppCategoriesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/(orders)/orders/$id': {
      id: '/(orders)/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof ordersOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/products/': {
      id: '/_authed/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AuthedAppProductsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/orders/': {
      id: '/_authed/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AuthedAppOrdersIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/inventory/': {
      id: '/_authed/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthedAppInventoryIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/dashboard/': {
      id: '/_authed/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthedAppDashboardIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/customers/': {
      id: '/_authed/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthedAppCustomersIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/coupons/': {
      id: '/_authed/app/coupons/'
      path: '/coupons'
      fullPath: '/app/coupons/'
      preLoaderRoute: typeof AuthedAppCouponsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/products/new': {
      id: '/_authed/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AuthedAppProductsNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/orders/$id': {
      id: '/_authed/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AuthedAppOrdersIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/inventory/adjustment': {
      id: '/_authed/app/inventory/adjustment'
      path: '/inventory/adjustment'
      fullPath: '/app/inventory/adjustment'
      preLoaderRoute: typeof AuthedAppInventoryAdjustmentRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/customers/$customerId': {
      id: '/_authed/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AuthedAppCustomersCustomerIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/coupons/new': {
      id: '/_authed/app/coupons/new'
      path: '/coupons/new'
      fullPath: '/app/coupons/new'
      preLoaderRoute: typeof AuthedAppCouponsNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/(orders)/orders/$orderId/confirmation': {
      id: '/(orders)/orders/$orderId/confirmation'
      path: '/orders/$orderId/confirmation'
      fullPath: '/orders/$orderId/confirmation'
      preLoaderRoute: typeof ordersOrdersOrderIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app/products/$id/details': {
      id: '/_authed/app/products/$id/details'
      path: '/products/$id/details'
      fullPath: '/app/products/$id/details'
      preLoaderRoute: typeof AuthedAppProductsIdDetailsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/app/products/variants/$id/edit': {
      id: '/_authed/app/products/variants/$id/edit'
      path: '/products/variants/$id/edit'
      fullPath: '/app/products/variants/$id/edit'
      preLoaderRoute: typeof AuthedAppProductsVariantsIdEditRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppRouteChildren {
  AuthedAppCategoriesRoute: typeof AuthedAppCategoriesRoute
  AuthedAppDeliveryFeesRoute: typeof AuthedAppDeliveryFeesRoute
  AuthedAppProductOptionTypesRoute: typeof AuthedAppProductOptionTypesRoute
  AuthedAppReviewsRoute: typeof AuthedAppReviewsRoute
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppCouponsNewRoute: typeof AuthedAppCouponsNewRoute
  AuthedAppCustomersCustomerIdRoute: typeof AuthedAppCustomersCustomerIdRoute
  AuthedAppInventoryAdjustmentRoute: typeof AuthedAppInventoryAdjustmentRoute
  AuthedAppOrdersIdRoute: typeof AuthedAppOrdersIdRoute
  AuthedAppProductsNewRoute: typeof AuthedAppProductsNewRoute
  AuthedAppCouponsIndexRoute: typeof AuthedAppCouponsIndexRoute
  AuthedAppCustomersIndexRoute: typeof AuthedAppCustomersIndexRoute
  AuthedAppDashboardIndexRoute: typeof AuthedAppDashboardIndexRoute
  AuthedAppInventoryIndexRoute: typeof AuthedAppInventoryIndexRoute
  AuthedAppOrdersIndexRoute: typeof AuthedAppOrdersIndexRoute
  AuthedAppProductsIndexRoute: typeof AuthedAppProductsIndexRoute
  AuthedAppProductsIdDetailsRoute: typeof AuthedAppProductsIdDetailsRoute
  AuthedAppProductsVariantsIdEditRoute: typeof AuthedAppProductsVariantsIdEditRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppCategoriesRoute: AuthedAppCategoriesRoute,
  AuthedAppDeliveryFeesRoute: AuthedAppDeliveryFeesRoute,
  AuthedAppProductOptionTypesRoute: AuthedAppProductOptionTypesRoute,
  AuthedAppReviewsRoute: AuthedAppReviewsRoute,
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppCouponsNewRoute: AuthedAppCouponsNewRoute,
  AuthedAppCustomersCustomerIdRoute: AuthedAppCustomersCustomerIdRoute,
  AuthedAppInventoryAdjustmentRoute: AuthedAppInventoryAdjustmentRoute,
  AuthedAppOrdersIdRoute: AuthedAppOrdersIdRoute,
  AuthedAppProductsNewRoute: AuthedAppProductsNewRoute,
  AuthedAppCouponsIndexRoute: AuthedAppCouponsIndexRoute,
  AuthedAppCustomersIndexRoute: AuthedAppCustomersIndexRoute,
  AuthedAppDashboardIndexRoute: AuthedAppDashboardIndexRoute,
  AuthedAppInventoryIndexRoute: AuthedAppInventoryIndexRoute,
  AuthedAppOrdersIndexRoute: AuthedAppOrdersIndexRoute,
  AuthedAppProductsIndexRoute: AuthedAppProductsIndexRoute,
  AuthedAppProductsIdDetailsRoute: AuthedAppProductsIdDetailsRoute,
  AuthedAppProductsVariantsIdEditRoute: AuthedAppProductsVariantsIdEditRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface StoreRequiredRouteChildren {
  StoreRequiredCartRoute: typeof StoreRequiredCartRoute
  StoreRequiredProductsAllRoute: typeof StoreRequiredProductsAllRoute
  StoreRequiredCheckoutIndexRoute: typeof StoreRequiredCheckoutIndexRoute
}

const StoreRequiredRouteChildren: StoreRequiredRouteChildren = {
  StoreRequiredCartRoute: StoreRequiredCartRoute,
  StoreRequiredProductsAllRoute: StoreRequiredProductsAllRoute,
  StoreRequiredCheckoutIndexRoute: StoreRequiredCheckoutIndexRoute,
}

const StoreRequiredRouteWithChildren = StoreRequiredRoute._addFileChildren(
  StoreRequiredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRoute,
  AuthedRoute: AuthedRouteWithChildren,
  StoreRequiredRoute: StoreRequiredRouteWithChildren,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  PayTokenRoute: PayTokenRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ordersOrdersIdRoute: ordersOrdersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMercadopagoConnectRoute: ApiMercadopagoConnectRoute,
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
  ordersOrdersOrderIdConfirmationRoute: ordersOrdersOrderIdConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
