/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CartImport } from './routes/cart'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as CartIndexImport } from './routes/cart/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppProductsIndexImport } from './routes/app/products/index'
import { Route as AppProductsNewImport } from './routes/app/products/new'

// Create/Update Routes

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CartIndexRoute = CartIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CartRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppProductsIndexRoute = AppProductsIndexImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)

const AppProductsNewRoute = AppProductsNewImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexImport
      parentRoute: typeof CartImport
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewImport
      parentRoute: typeof AppImport
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CartRouteChildren {
  CartIndexRoute: typeof CartIndexRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartIndexRoute: CartIndexRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/cart/': typeof CartIndexRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/products': typeof AppProductsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/cart': typeof CartIndexRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/products': typeof AppProductsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/cart/': typeof CartIndexRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/products/': typeof AppProductsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cart'
    | '/app/'
    | '/cart/'
    | '/app/products/new'
    | '/app/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/cart' | '/app/products/new' | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cart'
    | '/app/'
    | '/cart/'
    | '/app/products/new'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CartRoute: typeof CartRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CartRoute: CartRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/cart"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/",
        "/app/products/new",
        "/app/products/"
      ]
    },
    "/cart": {
      "filePath": "cart.tsx",
      "children": [
        "/cart/"
      ]
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/cart/": {
      "filePath": "cart/index.tsx",
      "parent": "/cart"
    },
    "/app/products/new": {
      "filePath": "app/products/new.tsx",
      "parent": "/app"
    },
    "/app/products/": {
      "filePath": "app/products/index.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
