/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AppRouteImport } from './routes/app'
import { Route as StoreRouteImport } from './routes/$store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews.new'
import { Route as ProductsAllRouteImport } from './routes/products/all'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as AppReviewsRouteImport } from './routes/app/reviews'
import { Route as AppDeliveryFeesRouteImport } from './routes/app/delivery-fees'
import { Route as AppCategoriesRouteImport } from './routes/app/categories'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppCouponsIndexRouteImport } from './routes/app/coupons/index'
import { Route as OrdersOrderIdConfirmationRouteImport } from './routes/orders/$orderId.confirmation'
import { Route as AppProductsNewRouteImport } from './routes/app/products/new'
import { Route as AppOrdersOrderIdRouteImport } from './routes/app/orders/$orderId'
import { Route as AppCouponsNewRouteImport } from './routes/app/coupons/new'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/$store',
  path: '/$store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/reviews/new',
  path: '/reviews/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryFeesRoute = AppDeliveryFeesRouteImport.update({
  id: '/delivery-fees',
  path: '/delivery-fees',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsIndexRoute = AppCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AppRoute,
} as any)
const OrdersOrderIdConfirmationRoute =
  OrdersOrderIdConfirmationRouteImport.update({
    id: '/$orderId/confirmation',
    path: '/$orderId/confirmation',
    getParentRoute: () => OrdersRoute,
  } as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsNewRoute = AppCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/delivery-fees': typeof AppDeliveryFeesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/all': typeof ProductsAllRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/app/': typeof AppIndexRoute
  '/app/coupons/new': typeof AppCouponsNewRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/orders/$orderId/confirmation': typeof OrdersOrderIdConfirmationRoute
  '/app/coupons': typeof AppCouponsIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/delivery-fees': typeof AppDeliveryFeesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/all': typeof ProductsAllRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/app': typeof AppIndexRoute
  '/app/coupons/new': typeof AppCouponsNewRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/orders/$orderId/confirmation': typeof OrdersOrderIdConfirmationRoute
  '/app/coupons': typeof AppCouponsIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$store': typeof StoreRoute
  '/app': typeof AppRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/delivery-fees': typeof AppDeliveryFeesRoute
  '/app/reviews': typeof AppReviewsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/all': typeof ProductsAllRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/app/': typeof AppIndexRoute
  '/app/coupons/new': typeof AppCouponsNewRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/orders/$orderId/confirmation': typeof OrdersOrderIdConfirmationRoute
  '/app/coupons/': typeof AppCouponsIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$store'
    | '/app'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/returns'
    | '/terms'
    | '/app/categories'
    | '/app/delivery-fees'
    | '/app/reviews'
    | '/orders/$id'
    | '/products/$slug'
    | '/products/all'
    | '/reviews/new'
    | '/app/'
    | '/app/coupons/new'
    | '/app/orders/$orderId'
    | '/app/products/new'
    | '/orders/$orderId/confirmation'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$store'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/returns'
    | '/terms'
    | '/app/categories'
    | '/app/delivery-fees'
    | '/app/reviews'
    | '/orders/$id'
    | '/products/$slug'
    | '/products/all'
    | '/reviews/new'
    | '/app'
    | '/app/coupons/new'
    | '/app/orders/$orderId'
    | '/app/products/new'
    | '/orders/$orderId/confirmation'
    | '/app/coupons'
    | '/app/dashboard'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/$store'
    | '/app'
    | '/cart'
    | '/checkout'
    | '/faq'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/products'
    | '/returns'
    | '/terms'
    | '/app/categories'
    | '/app/delivery-fees'
    | '/app/reviews'
    | '/orders/$id'
    | '/products/$slug'
    | '/products/all'
    | '/reviews/new'
    | '/app/'
    | '/app/coupons/new'
    | '/app/orders/$orderId'
    | '/app/products/new'
    | '/orders/$orderId/confirmation'
    | '/app/coupons/'
    | '/app/dashboard/'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRoute
  AppRoute: typeof AppRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ReturnsRoute: typeof ReturnsRoute
  TermsRoute: typeof TermsRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$store': {
      id: '/$store'
      path: '/$store'
      fullPath: '/$store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/reviews/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/all': {
      id: '/products/all'
      path: '/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery-fees': {
      id: '/app/delivery-fees'
      path: '/delivery-fees'
      fullPath: '/app/delivery-fees'
      preLoaderRoute: typeof AppDeliveryFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coupons/': {
      id: '/app/coupons/'
      path: '/coupons'
      fullPath: '/app/coupons'
      preLoaderRoute: typeof AppCouponsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/orders/$orderId/confirmation': {
      id: '/orders/$orderId/confirmation'
      path: '/$orderId/confirmation'
      fullPath: '/orders/$orderId/confirmation'
      preLoaderRoute: typeof OrdersOrderIdConfirmationRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$orderId': {
      id: '/app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coupons/new': {
      id: '/app/coupons/new'
      path: '/coupons/new'
      fullPath: '/app/coupons/new'
      preLoaderRoute: typeof AppCouponsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDeliveryFeesRoute: typeof AppDeliveryFeesRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCouponsNewRoute: typeof AppCouponsNewRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCouponsIndexRoute: typeof AppCouponsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDeliveryFeesRoute: AppDeliveryFeesRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCouponsNewRoute: AppCouponsNewRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCouponsIndexRoute: AppCouponsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersOrderIdConfirmationRoute: typeof OrdersOrderIdConfirmationRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersOrderIdConfirmationRoute: OrdersOrderIdConfirmationRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsAllRoute: typeof ProductsAllRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsAllRoute: ProductsAllRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRoute,
  AppRoute: AppRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ReturnsRoute: ReturnsRoute,
  TermsRoute: TermsRoute,
  ReviewsNewRoute: ReviewsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
